SET VERIFY OFF;
SET SERVEROUTPUT ON;

DECLARE
	A money.taka%TYPE;
	B money.taka%TYPE;
	C money.taka%TYPE;

BEGIN
	A:=&A;
	B:=&B;
	C:=A+B;
	/*DBMS_OUTPUT.PUT_LINE(C);*/
	IF C<170 THEN
		INSERT into MONEY(ID,NAME,TAKA) VALUES(7, 'A', C+10);
	ELSIF C>=170 AND C<=210 THEN
		INSERT into MONEY(ID,NAME,TAKA) VALUES(7, 'B', C+30);
	ELSE
		INSERT into MONEY(ID,NAME,TAKA) VALUES(7, 'C', C);
	END IF;

END;
/